# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool: 'Azure Pipelines'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

    
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: UseDotNet@2
  displayName: 'creating the faremwork'
  inputs:
    packageType: 'sdk'
    version: '5.0.408'
    includePreviewVersions: true
    performMultiLevelLookup: true
- task: VSBuild@1
  inputs:
    solution: '**\*.sln' 
    vsVersion: 'latest'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
